### PR TITLE
intro.tex: Replace Arm with ARM

### PR DESCRIPTION
**Pull request by gedare**

### CODE REVIEW

**Comment by gedare** [comment]
This one may be a bit debatable. I think the company has switched its usage over time.

**Comment by cento** [comment]
Arm is correct. The new style is the official one since 2017, if I remember correctly

**Comment by giactra** [comment]
https://github.com/darchr/gem5-20-paper/issues/33

**Comment by giactra** [comment]
And this is my PR https://github.com/darchr/gem5-20-paper/pull/35 (going in the opposite direction as this one)

**Comment by gedare** [comment]
I prefer the approach suggested in #35 by @giactra

**Pull request closed without merging**
